### ISSUE TITLE
Conexion de Base de Datos

### ISSUE THREAD

**Issue by Ariadnamonserrat10** [SistemasTecTlaxiaco/actividad-10-conexion-a-bases-de-datos-equipo-buscadores-de-datos#1]
* Roldan Uriel Arcadio Avila
* Pedro Garcia Garcia
* Ariadna Monserrat López Aparicio

[Conexion de Base de Datos.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-conexion-a-bases-de-datos-equipo-buscadores-de-datos/files/15488169/Conexion.de.Base.de.Datos.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
